// Contains all blog post data to be shared across blog components
export const allBlogPosts = [
  {
    id: "1",
    title: "The Rising Threat of Ransomware and How to Protect Your Organization",
    content: [
      "Ransomware attacks have increased by 150% in the last year, with organizations of all sizes falling victim to these devastating cyber threats. The average ransom payment has also increased, now exceeding $200,000 per incident, with some demands reaching millions of dollars.",
      "But the ransom itself is only part of the cost. Organizations face significant downtime, recovery expenses, and potential reputational damage that can far exceed the ransom amount. Understanding this evolving threat landscape is essential for developing effective protection strategies.",
      "## What Makes Ransomware So Dangerous",
      "Modern ransomware attacks have evolved into sophisticated operations, often employing a double-extortion model where criminals not only encrypt data but first exfiltrate it and threaten to publish sensitive information. This tactic puts pressure on organizations to pay even if they have proper backups.",
      "Ransomware groups are also increasingly targeting critical infrastructure and essential services, as seen in high-profile attacks against healthcare organizations, fuel pipelines, and food suppliers. These attacks have demonstrated the potential for real-world harm beyond just financial damage.",
      "## Effective Protection Strategies",
      "While no security approach can guarantee complete protection, organizations can significantly reduce their risk by implementing a comprehensive security strategy:",
      "### 1. Maintain Robust Backup Systems",
      "Implement the 3-2-1 backup rule: maintain three copies of your data on two different media types with one copy stored off-site. Regularly test your backup restoration processes to ensure they work when needed.",
      "### 2. Implement Zero Trust Security",
      "Move beyond traditional perimeter-based security to a Zero Trust model that verifies every user and device attempting to access your resources, regardless of location.",
      "### 3. Deploy Advanced Endpoint Protection",
      "Modern endpoint protection solutions use behavioral analysis and machine learning to detect and block ransomware before it can encrypt your files.",
      "### 4. Conduct Regular Security Training",
      "Employees remain the first line of defense. Regular security awareness training helps staff recognize phishing attempts and other social engineering tactics used to deliver ransomware.",
      "### 5. Develop an Incident Response Plan",
      "Create and regularly test a comprehensive incident response plan that details exactly how your organization will respond to a ransomware attack.",
      "## The Role of Government and Industry Cooperation",
      "Recent initiatives from government agencies are helping organizations combat ransomware. The Cybersecurity and Infrastructure Security Agency (CISA) has published detailed ransomware guides and the FBI's Internet Crime Complaint Center provides valuable threat intelligence.",
      "Industry partnerships are also emerging to share threat intelligence and best practices. These collaborative efforts are essential in the fight against increasingly sophisticated criminal organizations.",
      "## Conclusion",
      "As ransomware continues to evolve, organizations must adopt a proactive security posture. By implementing a defense-in-depth strategy and staying informed about emerging threats, you can significantly reduce your risk of becoming the next ransomware victim.",
      "Remember that prevention is always less costly than recovery. Investing in robust security measures today can protect your organization from potentially devastating attacks tomorrow."
    ].join('\n\n'),
    date: "May 15, 2023",
    readTime: "8 min read",
    author: "Elena Rodriguez",
    authorTitle: "Chief Security Analyst",
    authorImage: "https://randomuser.me/api/portraits/women/23.jpg",
    category: "Threat Intelligence",
    image: "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?auto=format&fit=crop&w=1200&q=80",
    tags: ["Ransomware", "Threat Protection", "Security Strategy", "Zero Trust"]
  },
  {
    id: "2",
    title: "Zero Trust Security: Beyond the Buzzword",
    content: [
      "Zero Trust is more than just a security model—it's a comprehensive approach to protecting your most valuable assets in today's complex digital landscape.",
      "The traditional security model of 'trust but verify' is no longer sufficient in an era where perimeters are dissolving and threats can come from both inside and outside an organization.",
      "## The Core Principles of Zero Trust",
      "At its core, Zero Trust operates on the principle of 'never trust, always verify.' This means treating every access request as though it originates from an untrusted network, regardless of whether it comes from inside or outside your corporate perimeter.",
      "Key components of a Zero Trust architecture include:",
      "### 1. Verify explicitly",
      "Always authenticate and authorize based on all available data points, including user identity, location, device health, service or workload, data classification, and anomalies.",
      "### 2. Use least privilege access",
      "Limit user access with Just-In-Time and Just-Enough-Access to protect both data and productivity.",
      "### 3. Assume breach",
      "Minimize blast radius and segment access. Verify end-to-end encryption and use analytics to improve defenses.",
      "## Implementing Zero Trust",
      "Moving to a Zero Trust model isn't an overnight process. It requires a phased approach that typically involves these steps:",
      "### 1. Define your protect surface",
      "Identify your most critical data, applications, assets, and services (the 'protect surface') rather than trying to secure the entire attack surface.",
      "### 2. Map transaction flows",
      "Understand how traffic moves across your network to determine how to properly enforce controls.",
      "### 3. Design your Zero Trust architecture",
      "Implement micro-perimeters around your protect surface, using next-generation firewalls as segmentation gateways.",
      "### 4. Create Zero Trust policies",
      "Develop policies that follow the principle of least privileged access. Allow only known allowed traffic or applications.",
      "### 5. Monitor and maintain the network",
      "Continuously inspect and log all traffic, using analytics to improve your security posture over time.",
      "## Common Challenges and Solutions",
      "Organizations often face several challenges when implementing Zero Trust:",
      "### Legacy systems compatibility",
      "Solution: Use proxies or API gateways to extend Zero Trust principles to legacy applications that weren't designed with modern authentication in mind.",
      "### User experience concerns",
      "Solution: Implement risk-based authentication that only steps up verification when unusual patterns are detected, reducing friction for regular users.",
      "### Complexity in implementation",
      "Solution: Start small with clearly defined use cases and expand gradually rather than attempting a complete overhaul at once.",
      "## Real-World Success Stories",
      "Many organizations have successfully implemented Zero Trust with impressive results:",
      "- A financial services company reduced their attack surface by 90% after implementing network micro-segmentation",
      "- A healthcare provider cut security incidents by 60% within six months of adopting a Zero Trust model",
      "- A government agency reported 85% faster detection of threats through continuous monitoring and analytics",
      "## Conclusion",
      "Zero Trust isn't just a technology solution—it's a security strategy that acknowledges the reality of today's threat landscape. By implementing the core principles of Zero Trust, organizations can significantly improve their security posture and reduce the risk of breaches.",
      "The journey to Zero Trust may be challenging, but the security benefits make it well worth the effort in an era where traditional perimeters no longer exist."
    ].join('\n\n'),
    date: "April 28, 2023",
    readTime: "10 min read",
    author: "Michael Lee",
    authorTitle: "Network Security Architect",
    authorImage: "https://randomuser.me/api/portraits/men/32.jpg",
    category: "Security Strategy",
    image: "https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?auto=format&fit=crop&w=600&q=80",
    tags: ["Zero Trust", "Network Security", "Identity Management"]
  },
  {
    id: "3",
    title: "Cloud Security Best Practices for 2023",
    content: [
      "As more organizations migrate to the cloud, understanding these security best practices is essential for protecting your data and applications.",
      "Cloud computing offers tremendous benefits in terms of scalability, cost-efficiency, and flexibility, but it also introduces new security challenges that organizations must address.",
      "## Key Cloud Security Best Practices",
      "### 1. Implement Strong Identity and Access Management",
      "Use multi-factor authentication (MFA) for all users, especially privileged accounts. Implement the principle of least privilege and regularly review and remove unused accounts and excessive permissions.",
      "### 2. Encrypt Data at Rest and in Transit",
      "Ensure all sensitive data is encrypted both when stored and when moving between services. Manage encryption keys carefully and consider using customer-managed keys where possible.",
      "### 3. Secure Your Cloud Configuration",
      "Misconfigurations are one of the leading causes of cloud security incidents. Use cloud security posture management (CSPM) tools to continuously scan for and remediate misconfigurations.",
      "### 4. Monitor Cloud Environments",
      "Implement comprehensive logging and monitoring across all cloud services. Use cloud-native security tools along with third-party solutions to gain visibility into potential threats.",
      "## Cloud Security Challenges by Service Model",
      "Different cloud service models (IaaS, PaaS, SaaS) present different security challenges and responsibilities:",
      "### Infrastructure as a Service (IaaS)",
      "In IaaS environments like AWS EC2, Azure VMs, or Google Compute Engine, you're responsible for securing the operating system, applications, and data. The cloud provider only secures the underlying infrastructure.",
      "Key focus areas for IaaS security include:",
      "- Hardening operating systems",
      "- Patch management",
      "- Network security controls",
      "- Host-based intrusion detection/prevention",
      "### Platform as a Service (PaaS)",
      "With PaaS offerings like AWS Elastic Beanstalk, Azure App Service, or Google App Engine, the provider manages the operating system while you focus on applications and data.",
      "Security priorities for PaaS include:",
      "- Secure code development",
      "- Strong authentication and authorization",
      "- Data protection",
      "- API security",
      "### Software as a Service (SaaS)",
      "For SaaS applications like Microsoft 365, Salesforce, or Google Workspace, the provider handles most security aspects, but you remain responsible for:",
      "- User access management",
      "- Data classification and protection",
      "- Compliance requirements",
      "- Integration security",
      "## Multi-Cloud Security Considerations",
      "Organizations using multiple cloud providers face additional challenges:",
      "### 1. Consistent security policies",
      "Implement consistent policies across all cloud environments to prevent security gaps.",
      "### 2. Centralized visibility",
      "Use cloud-agnostic security tools to gain unified visibility across different cloud providers.",
      "### 3. Identity management",
      "Implement federated identity solutions to manage access consistently across clouds.",
      "## Moving Forward: Cloud Security Maturity",
      "Building a mature cloud security program is an evolutionary process:",
      "### Phase 1: Foundation",
      "Start with fundamentals like IAM, encryption, and basic monitoring.",
      "### Phase 2: Standardization",
      "Develop and enforce security standards and automation across cloud resources.",
      "### Phase 3: Optimization",
      "Implement advanced threat detection, automated remediation, and continuous compliance monitoring.",
      "## Conclusion",
      "Cloud security is a shared responsibility between you and your cloud provider. By understanding your security obligations and implementing these best practices, you can enjoy the benefits of cloud computing while effectively managing risks.",
      "Remember to regularly review and update your cloud security strategy as both the threat landscape and cloud technologies continue to evolve."
    ].join('\n\n'),
    date: "April 15, 2023",
    readTime: "12 min read",
    author: "Sarah Johnson",
    authorTitle: "Cloud Security Specialist",
    authorImage: "https://randomuser.me/api/portraits/women/45.jpg",
    category: "Cloud Security",
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=600&q=80",
    tags: ["Cloud Security", "AWS", "Azure", "Data Protection"]
  },
  {
    id: "4",
    title: "The Role of AI in Modern Cybersecurity",
    content: [
      "Artificial intelligence is transforming how we detect and respond to threats. Here's how AI is changing the security landscape.",
      "As cyber threats grow in sophistication and volume, traditional security approaches struggle to keep pace. AI and machine learning technologies offer powerful new capabilities to enhance detection and response.",
      "## How AI is Transforming Cybersecurity",
      "### 1. Advanced Threat Detection",
      "AI systems can analyze vast amounts of data to identify patterns and anomalies that might indicate a security threat, often detecting novel attacks that signature-based systems would miss.",
      "### 2. Automated Response Capabilities",
      "When threats are detected, AI can automatically initiate response actions, containing threats in real-time before significant damage occurs.",
      "### 3. Reducing Alert Fatigue",
      "By consolidating and prioritizing alerts, AI helps security teams focus on genuine threats rather than being overwhelmed by false positives.",
      "## AI Applications in Cybersecurity",
      "AI technologies are being applied across multiple security domains:",
      "### Endpoint Protection",
      "Next-generation antivirus solutions use machine learning to identify malicious code based on behavior rather than signatures, enabling detection of previously unseen malware variants.",
      "### Network Security",
      "AI-powered network monitoring tools establish baselines of normal activity and flag unusual patterns that might indicate an intrusion, data exfiltration, or lateral movement by attackers.",
      "### Email Security",
      "Natural language processing helps identify sophisticated phishing attempts by analyzing email context, sender behavior, and linguistic patterns that might escape traditional filters.",
      "### User Behavior Analytics",
      "AI systems monitor user activities to establish normal behavior profiles and detect anomalies that might indicate a compromised account or insider threat.",
      "## The Human-AI Partnership",
      "While AI brings powerful capabilities to cybersecurity, human expertise remains essential:",
      "### Human Oversight",
      "Security professionals provide critical context and judgment when evaluating AI-generated alerts, reducing false positives and ensuring appropriate responses.",
      "### AI Training",
      "Security teams continuously train and refine AI systems by providing feedback on detection accuracy and evolving threat patterns.",
      "### Strategic Decision-Making",
      "Humans establish security policies, risk thresholds, and response protocols that guide AI operations.",
      "## Challenges and Limitations",
      "AI security technologies face several challenges:",
      "### Adversarial Attacks",
      "Attackers can deliberately manipulate AI systems through techniques like poisoning training data or crafting inputs designed to evade detection.",
      "### Data Quality Issues",
      "AI effectiveness depends on high-quality training data, which can be difficult to obtain for rare or emerging threat types.",
      "### Explainability Concerns",
      "Some AI systems function as 'black boxes,' making it difficult to understand why certain decisions were made—a significant issue for regulatory compliance and incident response.",
      "## The Future of AI in Cybersecurity",
      "Looking ahead, we can expect several developments:",
      "### 1. Self-healing systems",
      "Future AI security systems will not only detect and respond to threats but automatically strengthen defenses based on lessons learned.",
      "### 2. Predictive security",
      "Advanced analytics will increasingly shift from reactive to predictive capabilities, identifying vulnerabilities before they can be exploited.",
      "### 3. AI-vs-AI warfare",
      "As attackers deploy their own AI technologies to probe defenses and automate attacks, defensive AI will evolve to counter these sophisticated threats.",
      "## Conclusion",
      "AI represents a significant advancement in cybersecurity capabilities, helping organizations detect and respond to threats with greater speed and accuracy than ever before. However, the most effective security approaches will combine AI capabilities with human expertise, leveraging the strengths of both to create robust defenses against evolving threats.",
      "As AI security technologies continue to mature, organizations that effectively integrate these tools into their security operations will gain significant advantages in protecting their critical assets and data."
    ].join('\n\n'),
    date: "March 22, 2023",
    readTime: "11 min read",
    author: "David Kim",
    authorTitle: "AI Security Researcher",
    authorImage: "https://randomuser.me/api/portraits/men/67.jpg",
    category: "Technology",
    image: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=600&q=80",
    tags: ["AI", "Machine Learning", "Threat Detection"]
  },
  {
    id: "5",
    title: "Securing Your Remote Workforce",
    content: [
      "With remote work becoming permanent for many organizations, addressing these security challenges is more important than ever.",
      "The rapid shift to remote work has expanded the attack surface for many organizations, creating new security challenges that require innovative solutions.",
      "## Key Remote Work Security Challenges",
      "### 1. Unsecured Home Networks",
      "Home networks typically lack the security controls present in corporate environments, making them more vulnerable to compromise.",
      "### 2. Personal Device Usage",
      "When employees use personal devices for work (BYOD), organizations have less control over the security of these endpoints.",
      "### 3. Increased Phishing Attacks",
      "Remote workers are prime targets for phishing attacks that exploit COVID-19 concerns and remote work themes.",
      "## Essential Remote Work Security Controls",
      "To address these challenges, organizations should implement several key security measures:",
      "### Secure Remote Access",
      "A robust virtual private network (VPN) solution is essential for creating encrypted connections between remote workers and corporate resources. However, modern security approaches are increasingly moving beyond traditional VPNs to Zero Trust Network Access (ZTNA) solutions that provide more granular control and better security.",
      "Key features to look for include:",
      "- Multi-factor authentication integration",
      "- Split tunneling capabilities",
      "- Automatic connection monitoring",
      "- Seamless user experience",
      "### Endpoint Protection",
      "Remote devices require comprehensive security controls including:",
      "- Next-generation antivirus with behavior-based detection",
      "- Host-based firewalls",
      "- Automated patch management",
      "- Disk encryption",
      "- Application control",
      "- Endpoint detection and response (EDR) capabilities",
      "### Identity and Access Management",
      "Strengthen access controls with:",
      "- Multi-factor authentication for all remote access",
      "- Risk-based authentication that considers location, device, and behavior",
      "- Privileged access management for administrative accounts",
      "- Single sign-on (SSO) to reduce password fatigue",
      "## Securing Collaboration Tools",
      "Remote work relies heavily on digital collaboration tools, which must be properly secured:",
      "### Video Conferencing",
      "- Enable meeting passwords and waiting rooms",
      "- Utilize host controls to manage participants",
      "- Keep applications updated to address security vulnerabilities",
      "- Train users on security features and privacy settings",
      "### Cloud File Sharing",
      "- Implement appropriate access controls and permissions",
      "- Enable versioning and recovery options",
      "- Consider data loss prevention (DLP) tools",
      "- Audit sharing activities regularly",
      "## Remote Work Security Policies",
      "Develop and implement policies specifically addressing remote work security:",
      "### Acceptable Use Policy",
      "Clearly define expectations for company equipment and resources when used remotely.",
      "### BYOD Policy",
      "If personal devices are permitted for work, establish minimum security requirements and management capabilities.",
      "### Incident Response Plan",
      "Update procedures to address remote work scenarios and ensure employees know how to report security incidents.",
      "## Security Awareness Training",
      "Adapt training for the remote environment with focus on:",
      "- Recognizing phishing attacks targeting remote workers",
      "- Securing home networks and personal devices",
      "- Safe use of collaboration tools",
      "- Physical security for remote workspaces",
      "## Monitoring and Visibility",
      "Maintain security visibility across your remote workforce with:",
      "- Cloud-based security monitoring",
      "- User and entity behavior analytics (UEBA)",
      "- Data loss prevention (DLP) solutions",
      "- Network traffic analysis tools",
      "## Conclusion",
      "Securing a remote workforce requires a multi-layered approach that combines technology, policy, and education. By implementing these security measures, organizations can enable productive remote work while effectively managing the associated security risks.",
      "Remember that securing remote work is an ongoing process that must evolve as threats and work patterns change. Regular assessment and adjustment of your security controls is essential for long-term success."
    ].join('\n\n'),
    date: "March 10, 2023",
    readTime: "14 min read",
    author: "Jessica Martinez",
    authorTitle: "Remote Security Expert",
    authorImage: "https://randomuser.me/api/portraits/women/63.jpg",
    category: "Business Security",
    image: "https://images.unsplash.com/photo-1521898284481-a5ec348cb555?auto=format&fit=crop&w=600&q=80",
    tags: ["Remote Work", "VPN", "Endpoint Security"]
  },
  {
    id: "6",
    title: "GDPR Compliance: What You Need to Know in 2023",
    content: [
      "Stay up to date with the latest GDPR requirements and how they impact your organization's data handling practices.",
      "Five years after its implementation, the General Data Protection Regulation (GDPR) continues to evolve through court decisions, regulatory guidance, and enforcement actions.",
      "## Recent GDPR Developments",
      "### 1. Increased Enforcement Activity",
      "Regulatory authorities are stepping up enforcement, with larger fines being imposed for violations. Organizations must ensure their compliance measures are robust and up-to-date.",
      "### 2. International Data Transfers",
      "Following the Schrems II decision, requirements for transferring data outside the EU have become more stringent. Organizations must implement additional safeguards when using standard contractual clauses.",
      "### 3. The Right to Be Forgotten",
      "Recent court decisions have clarified the scope of the right to erasure, balancing privacy rights against other legitimate interests.",
      "## Core GDPR Principles in Practice",
      "The GDPR is built around key principles that should guide all your data processing activities:",
      "### Lawful, Fair, and Transparent Processing",
      "Every instance of personal data processing must have a valid legal basis. The six lawful bases are:",
      "1. **Consent**: Must be freely given, specific, informed, and unambiguous",
      "2. **Contract**: Processing necessary to fulfill contractual obligations",
      "3. **Legal obligation**: Processing required to comply with the law",
      "4. **Vital interests**: Processing to protect someone's life",
      "5. **Public interest**: Processing necessary for tasks in the public interest",
      "6. **Legitimate interests**: Processing justified by legitimate business purposes that don't override individual rights",
      "Organizations must clearly document which legal basis applies to each processing activity.",
      "### Purpose Limitation",
      "Personal data should only be collected for specified, explicit, and legitimate purposes. Before collecting data, clearly define why you need it and don't use it for incompatible purposes later.",
      "### Data Minimization",
      "Only collect the personal data that's actually necessary for your stated purposes. Regularly review your data collection practices to eliminate unnecessary fields and datasets.",
      "### Accuracy",
      "Take reasonable steps to ensure personal data is accurate and up-to-date. Implement processes for individuals to review and correct their data.",
      "### Storage Limitation",
      "Don't keep personal data for longer than necessary. Develop and enforce data retention policies that specify how long different types of data should be kept.",
      "### Integrity and Confidentiality",
      "Implement appropriate security measures to protect personal data from unauthorized access, accidental loss, or destruction.",
      "## Practical GDPR Compliance Steps",
      "### 1. Update Your Data Processing Records",
      "Maintain comprehensive records of all data processing activities, including:",
      "- Categories of personal data collected",
      "- Purposes of processing",
      "- Legal basis for each purpose",
      "- Data retention periods",
      "- Security measures implemented",
      "- Third parties with whom data is shared",
      "### 2. Strengthen Consent Mechanisms",
      "If you rely on consent as your legal basis for processing:",
      "- Use clear, plain language to request consent",
      "- Make it as easy to withdraw consent as to give it",
      "- Don't use pre-ticked boxes or other default consent methods",
      "- Keep detailed records of when and how consent was obtained",
      "### 3. Review International Data Transfers",
      "For data transferred outside the European Economic Area (EEA):",
      "- Implement appropriate safeguards like Standard Contractual Clauses (SCCs)",
      "- Conduct and document transfer impact assessments",
      "- Consider data localization for highly sensitive information",
      "### 4. Enhance Individual Rights Procedures",
      "Streamline your processes for handling data subject requests, including:",
      "- Right to access personal data",
      "- Right to rectification of inaccurate data",
      "- Right to erasure ('right to be forgotten')",
      "- Right to restriction of processing",
      "- Right to data portability",
      "- Right to object to processing",
      "### 5. Implement Privacy by Design",
      "Integrate data protection considerations into new projects and systems from the earliest stages:",
      "- Conduct Data Protection Impact Assessments (DPIAs) for high-risk processing",
      "- Build privacy controls into product development workflows",
      "- Minimize data collection and processing by default",
      "## Common GDPR Compliance Pitfalls",
      "Avoid these frequent compliance mistakes:",
      "### Inadequate Security Measures",
      "Implement technical and organizational measures appropriate to the risk, including encryption, access controls, and regular security testing.",
      "### Poorly Managed Vendor Relationships",
      "Ensure all data processors have appropriate contractual obligations and verify their compliance regularly.",
      "### Ineffective Breach Response",
      "Develop and test a comprehensive data breach response plan to meet the 72-hour notification requirement.",
      "### Outdated Privacy Notices",
      "Regularly review and update privacy policies to reflect current processing activities and compliance measures.",
      "## Conclusion",
      "GDPR compliance isn't a one-time project but an ongoing program that requires regular attention and updates. By staying current with regulatory developments and implementing these practical compliance measures, organizations can both meet their legal obligations and build trust with customers and partners.",
      "Remember that good data protection practices aren't just about avoiding fines—they're fundamental to responsible business operations in our data-driven world."
    ].join('\n\n'),
    date: "February 28, 2023",
    readTime: "15 min read",
    author: "Thomas Anderson",
    authorTitle: "Privacy Compliance Officer",
    authorImage: "https://randomuser.me/api/portraits/men/91.jpg",
    category: "Compliance",
    image: "https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?auto=format&fit=crop&w=600&q=80",
    tags: ["GDPR", "Compliance", "Data Privacy"]
  }
];

export const blogCategories = [
  { name: "Threat Intelligence", count: 18 },
  { name: "Cloud Security", count: 12 },
  { name: "Security Strategy", count: 9 },
  { name: "Technology", count: 14 },
  { name: "Compliance", count: 8 },
  { name: "Business Security", count: 11 }
];

export const popularTags = [
  "Ransomware", "Cloud Security", "Zero Trust", "AI", "Compliance", 
  "GDPR", "Remote Work", "Threat Intelligence", "Data Privacy"
]; 